FROM node:22-slim

WORKDIR /backend

COPY package*.json ./

RUN npm install

RUN apt-get update && apt-get install -y netcat-openbsd

COPY . .

RUN chmod +x wait-for-db.sh

RUN ls -al /backend 

EXPOSE 3000

CMD ["npm", "start"]